# Generated by Django 2.0 on 2021-04-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offername', models.CharField(max_length=100)),
                ('startdate', models.DateField(max_length=12)),
                ('enddate', models.DateField(max_length=12)),
                ('discount_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('description', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=100)),
                ('prodDescription', models.TextField(max_length=500)),
                ('prod_quantity', models.BigIntegerField()),
                ('stock', models.CharField(default=None, max_length=20)),
                ('prodImg', models.ImageField(upload_to='images/')),
                ('prodPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminservice.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subName', models.CharField(max_length=100)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminservice.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcatid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminservice.Subcategory'),
        ),
        migrations.AddField(
            model_name='offer',
            name='prodid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminservice.Product'),
        ),
    ]
