# Generated by Django 2.0 on 2021-04-17 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminservice', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime_of_feedback', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback_message', models.TextField(max_length=10000)),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminservice.Product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User_register')),
            ],
        ),
    ]
